openapi: 3.0.0
info:
  description: "Event service"
  version: "1.0.0"
  title: "Event service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "alxminyaev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "0.0.0.0"
# basePath: "/auth"

servers:
  - url: "http://5.130.14.37:8080/event"
  - url: "http://localhost/event"
tags:
  - name: "OutStudyEvent"
    description: "Разовое мероприятие"
    externalDocs:
      description: "Find out more"
      url: "shorturl.at/bjwU5"
  - name: "OutStudyEventKind"
    description: "Вид мероприятия"
    externalDocs:
      description: "Find out more"
      url: "shorturl.at/bjwU5"


paths:
  /api/v1/outstudy-event:
    post:
      tags:
        - "OutStudyEvent"
      summary: "Create outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postOutStudyEvent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutStudyEventPostRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityIntCreatedResponse"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - "OutStudyEvent"
      summary: "Get list of  outstudy-events (Not implemented, HIGH Priority)"
      description: ""
      operationId: "getOutStudyEvents"
      parameters:
        - in: query
          required: true
          name: offset
          schema:
            type: integer
            format: int64
          description: The number of items to skip before starting to collect the result set
        - in: query
          required: true
          name: limit
          schema:
            type: integer
            format: int32
          description: The numbers of items to return
        - in: query
          name: dateStart
          schema:
            type: "string"
            format: "date-time"
            description: "UTC"
        - in: query
          name: dateEnd
          schema:
            type: "string"
            format: "date-time"
            description: "UTC"
        - in: query
          name: status
          schema:
            type: "integer"
            format: "int64"
        - in: query
          name: isConfirmed
          schema:
            type: "boolean"

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutStudyEventListResponse"

  /api/v1/outstudy-event/{id}:
    get:
      tags:
        - "OutStudyEvent"
      summary: "Get outstudy-event by id (Not implemented, LOW Priority)"
      description: ""
      operationId: "getByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of object to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutStudyEventGetResponseWithMembers"
        "404":
          description: "Not found"
    delete:
      tags:
        - "OutStudyEvent"
      summary: "Get outstudy-event by id (Not implemented, MEDIUM Priority)"
      description: ""
      operationId: "deleteEventByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of object to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
    put:
      tags:
        - "OutStudyEvent"
      summary: "Update outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "updateByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of object to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutStudyEventPostRequest'
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/outstudy-event/{id}/registration:
    post:
      tags:
        - "OutStudyEvent"
      summary: "User registration in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postRegistrationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - "OutStudyEvent"
      summary: "Deleting of user registration in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "deleteRegistrationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/v1/outstudy-event/{id}/user-confirm:
    post:
      tags:
        - "OutStudyEvent"
      summary: "User confirmation in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postConfirmationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserKeys'
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - "OutStudyEvent"
      summary: "Deleting of user confirmation in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "deleteConfirmationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"


  /api/v1/outstudy-eventkind:
    post:
      tags:
        - "OutStudyEventKind"
      summary: "Create OutStudyEventKind object"
      description: ""
      operationId: "postOutStudyEventKind"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutStudyEventKindPostRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityIntCreatedResponse"
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - "OutStudyEventKind"
      summary: "Get list of OutStudyEventKinds"
      description: ""
      operationId: "getOutStudyEventKinds"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventKindListOutStudyGetResponse"


  /api/v1/outstudy-eventkind/{id}:
    delete:
      tags:
        - "OutStudyEventKind"
      summary: "OutStudyEvent kind by id (Not implemented, MEDIUM Priority)"
      description: ""
      operationId: "deleteByOutStudyEventKindId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    OutStudyEventPostRequest:
      type: object
      required:
        - name
        - address
        - outstudyEventKindId
        - status
      properties:
        name:
          type: "string"
        description:
          type: "string"
        address:
          type: "string"
        dateStart:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateRegistrationEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        outstudyEventKindId:
          type: integer
          format: int32
        maxMembers:
          type: integer
          format: int32
          description: "-1 - not defended value"
        minMembers:
          type: integer
          format: int32
          description: "-1 - not defended value"
        status:
          type: integer
          format: int32
        isNeedMemberConfirmation:
          type: boolean


    OutStudyEventGetResponse:
      type: object
      required:
        - id
        - name
        - address
        - outstudyEventKind
        - status
        - isNeedMemberConfirmation
        - organizer
      properties:
        id:
          type: integer
          format: "int64"
        name:
          type: "string"
        description:
          type: "string"
        address:
          type: "string"
        dateStart:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateRegistrationEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        outstudyEventKind:
          type: integer
          format: int32
        maxMembers:
          type: integer
          format: int32
        minMembers:
          type: integer
          format: int32
        status:
          type: integer
          format: int32
        isNeedMemberConfirmation:
          type: boolean
        isConfirmed:
          type: boolean
        organizer:
          $ref: "#/components/schemas/OrganizerResponse"

    OutStudyEventGetResponseWithMembers:
      type: object
      properties:
        event:
          $ref: "#/components/schemas/OutStudyEventGetResponse"
        members:
          type: array
          items:
            $ref: "#/components/schemas/MemberResponse"

    OutStudyEventListResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/OutStudyEventGetResponse"

    OutStudyEventKindPostRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: "string"
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/OutStudyEventCriterionPostRequest'

    EventKindOutStudyGetResponse:
      type: object
      required:
        - id
        - name
        - criteria
      properties:
        id:
          type: integer
          format: int32
        name:
          type: "string"
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/OutStudyEventCriteria'

    EventKindListOutStudyGetResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/EventKindOutStudyGetResponse"

    OutStudyEventCriteria:
      required:
        - id
        - name
        - value
        - typeId
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        value:
          type: integer
          format: int32
        typeId:
          type: integer
          format: int32
          description: "1: ALL, 2: BY_RATING_PLACE, 3: CUSTOM"
        bottomPlace:
          type: integer
          format: int32
        topPlace:
          type: integer
          format: int32
    OutStudyEventCriterionPostRequest:
      required:
        - value
        - typeId
      type: object
      properties:
        name:
          type: string
        value:
          type: integer
          format: int32
        typeId:
          type: integer
          format: int32
          description: "1: ALL, 2: BY_RATING_PLACE, 3: CUSTOM"
        bottomPlace:
          type: integer
          format: int32
        topPlace:
          type: integer
          format: int32
    UserKeys:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          format: int64
          description: "User id"

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        field:
          type: "string"
        message:
          type: "string"

    EntityIntCreatedResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: "integer"
          format: "int32"
    EntityLongCreatedResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: "integer"
          format: "int64"

    OrganizerResponse:
      type: object
      required:
        - user
      properties:
        user:
          $ref: '#/components/schemas/User'

    MemberResponse:
      type: object
      required:
        - user
      properties:
        user:
          $ref: '#/components/schemas/User'
        isConfirmed:
          type: "boolean"

    User:
      type: object
      required:
        - id
        - roles
        - profile
      properties:
        id:
          type: integer
          format: int64
        roles:
          type: array
          items:
            type: integer
        profile:
          $ref: '#/components/schemas/Profile'


    Profile:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        middleName:
          type: "string"


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"