openapi: 3.0.0
info:
  description: "Event service"
  version: "1.0.0"
  title: "Event service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "alxminyaev@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "0.0.0.0"
# basePath: "/auth"

servers:
  - url: "http://localhost/event"
tags:
  - name: "OutStudyEvent"
    description: "Разовое мероприятие"
    externalDocs:
      description: "Find out more"
      url: "shorturl.at/bjwU5"
  - name: "OutStudyEventKind"
    description: "Вид мероприятия"
    externalDocs:
      description: "Find out more"
      url: "shorturl.at/bjwU5"


paths:
  /api/v1/outstudy-event:
    post:
      tags:
        - "OutStudyEvent"
      summary: "Create outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postOutStudyEvent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutStudyEventPostRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityIntCreatedResponse"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - "OutStudyEvent"
      summary: "Get list of  outstudy-events (Not implemented, HIGH Priority)"
      description: ""
      operationId: "getOutStudyEvents"
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            format: int64
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
          description: The numbers of items to return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutStudyEventListResponse"

  /api/v1/outstudy-event/{id}:
    get:
      tags:
        - "OutStudyEvent"
      summary: "Get outstudy-event by id (Not implemented, LOW Priority)"
      description: ""
      operationId: "getByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of object to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutStudyEventGetResponse"
        "404":
          description: "Not found"
    delete:
      tags:
        - "OutStudyEvent"
      summary: "Get outstudy-event by id (Not implemented, MEDIUM Priority)"
      description: ""
      operationId: "deleteEventByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of object to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
    put:
      tags:
        - "OutStudyEvent"
      summary: "Update outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "updateByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of object to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutStudyEventPostRequest'
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/outstudy-event/{id}/registration:
    post:
      tags:
        - "OutStudyEvent"
      summary: "User registration in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postRegistrationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - "OutStudyEvent"
      summary: "Deleting of user registration in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "deleteRegistrationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/v1/outstudy-event/{id}/user-confirm:
    post:
      tags:
        - "OutStudyEvent"
      summary: "User confirmation in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postConfirmationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserKeys'
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - "OutStudyEvent"
      summary: "Deleting of user confirmation in outstudy-event (Not implemented, HIGH Priority)"
      description: ""
      operationId: "deleteConfirmationByOutStudyEventId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserKeys'
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"


  /api/v1/outstudy-eventkind:
    post:
      tags:
        - "OutStudyEventKind"
      summary: "Create OutStudyEventKind object (Not implemented, HIGH Priority)"
      description: ""
      operationId: "postOutStudyEventKind"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutStudyEventKindPostRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityIntCreatedResponse"
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - "OutStudyEventKind"
      summary: "Get list of OutStudyEventKinds (Not implemented, HIGH Priority)"
      description: ""
      operationId: "getOutStudyEventKinds"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutStudyEventKindListGetResponse"


  /api/v1/outstudy-eventkind/{id}:
    delete:
      tags:
        - "OutStudyEventKind"
      summary: "OutStudyEvent kind by id (Not implemented, MEDIUM Priority)"
      description: ""
      operationId: "deleteByOutStudyEventKindId"
      parameters:
        - name: id
          in: path
          description: ID of outstudy-event
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        "404":
          description: "Not found"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    OutStudyEventPostRequest:
      type: object
      required:
        - name
        - address
        - outstudyEventKind
        - status
      properties:
        name:
          type: "string"
        description:
          type: "string"
        address:
          type: "string"
        dateStart:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateRegistrationEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        outstudyEventKind:
          type: integer
          format: int32
        maxMembers:
          type: integer
          format: int32
          description: "-1 - not defended value"
        minMembers:
          type: integer
          format: int32
          description: "-1 - not defended value"
        status:
          type: integer
          format: int32
        isNeedMemberConfirmation:
          type: boolean


    OutStudyEventGetResponse:
      type: object
      required:
        - id
        - name
        - address
        - outstudyEventKind
        - status
      properties:
        id:
          type: integer
          format: "int64"
        name:
          type: "string"
        description:
          type: "string"
        address:
          type: "string"
        dateStart:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        dateRegistrationEnd:
          type: "string"
          format: "date-time"
          description: "UTC"
        outstudyEventKind:
          type: integer
          format: int32
        maxMembers:
          type: integer
          format: int32
          description: "-1 - not defended value"
        minMembers:
          type: integer
          format: int32
          description: "-1 - not defended value"
        status:
          type: integer
          format: int32
        isNeedMemberConfirmation:
          type: boolean
    OutStudyEventListResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/OutStudyEventGetResponse"

    OutStudyEventKindPostRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: "string"

    OutStudyEventKindGetResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: "string"

    OutStudyEventKindListGetResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/OutStudyEventKindGetResponse"

    UserKeys:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: integer
          format: int64
        type:
          type: integer
          format: int32

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        field:
          type: "string"
        message:
          type: "string"

    EntityIntCreatedResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: "integer"
          format: "int64"
    EntityLongCreatedResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: "integer"
          format: "int32"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"