/**
* Event service
* Event service
*
* The version of the OpenAPI document: 1.0.0
* Contact: alxminyaev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.alxminyaev.feature.event.api.models

import dev.alxminyaev.feature.event.api.models.OutStudyEventCriteria

/**
 * 
 * @param id 
 * @param name 
 * @param criteria 
 */
data class EventKindOutStudyGetResponse (
    val id: kotlin.Int,
    val name: kotlin.String,
    val criteria: kotlin.Array<OutStudyEventCriteria>
) 

