/**
* Event service
* Event service
*
* The version of the OpenAPI document: 1.0.0
* Contact: alxminyaev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.alxminyaev.feature.event.api.models


/**
 * 
 * @param value 
 * @param typeId 1: ALL, 2: BY_RATING_PLACE, 3: CUSTOM
 * @param name 
 * @param bottomPlace 
 * @param topPlace 
 */
data class OutStudyEventCriterionPostRequest (
    val value: kotlin.Int,
    /* 1: ALL, 2: BY_RATING_PLACE, 3: CUSTOM */
    val typeId: kotlin.Int,
    val name: kotlin.String? = null,
    val bottomPlace: kotlin.Int? = null,
    val topPlace: kotlin.Int? = null
) 

