/**
* Event service
* Event service
*
* The version of the OpenAPI document: 1.0.0
* Contact: alxminyaev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.alxminyaev.feature.event.api.models


/**
 * 
 * @param status 1: IN_PROCESS, 2: ACCEPT, 3: REJECT
 */
data class RequestOutStudyEventApi (
    /* 1: IN_PROCESS, 2: ACCEPT, 3: REJECT */
    val status: kotlin.Int
) 

